### ISSUE TITLE
Running postgraphile as a docker container along with plugins throwing errors

### ISSUE THREAD

**Issue by rupalimishra-v2** [graphile/graphile.github.io#404]
sudo docker run -p 5200:5200 graphile/postgraphile --plugins @graphile/pg-pubsub --connection postgres:<testuser>:<testpwd>@rds-instance.testinstance.ap-south-1.rds.amazonaws.com:5432/db --enhance-graphiql --schema public --cors --disable-default-mutations --jwt-token-identifier public.jwt_token --jwt-secret <secret> --default-role no_access_role --show-error-stack --dynamic-json --body-size-limit 1MB --subscriptions

node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '@graphile/pg-pubsub'
Require stack:
- /postgraphile/build/postgraphile/cli.js
- /postgraphile/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at /postgraphile/build/postgraphile/cli.js:57:27
    at Array.map (<anonymous>)
    at extractPlugins (/postgraphile/build/postgraphile/cli.js:55:35)
    at Object.<anonymous> (/postgraphile/build/postgraphile/cli.js:67:62)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/postgraphile/build/postgraphile/cli.js', '/postgraphile/cli.js' ]
}

**Comment by rupalimishra-v2** [comment]
Without a --plugin flag it works fine, I tried installing the plugin using - npm install @graphile/pg-pubsub, still same error.
